### ISSUE TITLE
the webpage sidebar turn blank when open a new tab

### ISSUE THREAD

**Issue by notnotfish** [RabbitPair/colorful_sidepanel_tabs_extension#10]
**Describe the bug**
The bug is related to the webpage sidebar. When I open a new tab, the sidebar of the already opened tabs becomes blank.
It might have appeared after the last update.

**To Reproduce**
1. open any webpage. the webpage sidebar works normally.
2. open a new tab
3. switch to the already opened tab. the webpage sidebar turns blank

**Expected behavior**
fix it, thx

**Screenshots**
![image](https://github.com/user-attachments/assets/2b42879f-ccb2-4768-a22a-26d592004410)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 129.0.6668.101 (arm64)

**Additional context**
In fact, I have the same issue on another computer as well.

**Comment by ymlluo** [comment]
Thanks for your feedback!

this issue will be fixed in the next update
At present, the sidebar of the web page will be automatically inserted and rendered when the new page is opened, and the upcoming version will be modified to render when it is displayed, which can reduce the impact on the original web page. It is expected to be released in the next few days

**Comment by ymlluo** [comment]
The latest version, v2.12.0, has been released. Please update to the newest version and give it a try! If you have any questions or encounter any issues, feel free to reach out at any time.
