### ISSUE TITLE
Don't load discarded tabs on browser start

### ISSUE THREAD

**Issue by Daemonias** [RabbitPair/colorful_sidepanel_tabs_extension#13]
**Is your feature request related to a problem? Please describe.**
Whenever I open my browser all groups are loaded and every tab in every group is loading and the focus is swapping to the latest loaded tab. That means I'll have to wait till it's finished to use the browser.
**Describe the solution you'd like**
Have the addin load only the group which has the tab that was opened when the browser is closed. All tabs that were discarded should stay discarded until opened

**Comment by ymlluo** [comment]
The Chrome browser API does not support directly discarding tabs. I can
only create a tab first and then discard it. However, if I discard the tab
immediately after opening it, the title or icon will not be loaded. This
timing is not easy to grasp. I can understand the problem of lag and
waiting caused by opening a large number of tabs. I will try my best to
optimize it in the next version. It may be that discarding tabs may also
increase the delay time of opening windows. I will confirm it after testing.

Daemonias ***@***.***> 于2024年11月1日周五 20:40写道：

**Comment by ymlluo** [comment]
The latest version, v2.12.0, has been released. Please update to the newest version and give it a try! If you have any questions or encounter any issues, feel free to reach out at any time.
