### ISSUE TITLE
[two requests regarding the Tab-bar] Scrollable Tab-bar & Auto shortening/Expanding of groupnames

### ISSUE THREAD

**Issue by Daemonias** [RabbitPair/colorful_sidepanel_tabs_extension#9]
**Is your feature request related to a problem? Please describe.**
When opening a lot of groups my Tab-bar fills up to the point that some groups are reachable only through the sidepanel.
It helps to deactivate the Auto group but it also makes it a lot harder to find the relevant groups

**Describe the solution you'd like**

1. A scrollbar at the tab-bar so you can scroll it if its getting to long for my screen.
2. The option to have groupnames/icons autoshorten to a set or adjustable length.
       - have them either go back to fullsize on hovering or for the opened group only
       - have the fullname always in the tooltip

**Comment by ymlluo** [comment]
Thank you for your feedback! It might be helpful to provide some more details.

### First Question:
Are you referring to a **horizontal scrollbar**? If so, it might not be supported because the current minimum width is already quite wide. Adding a horizontal scrollbar could make the overall layout feel cluttered.

### Second Question:
This is a great suggestion.

1. **Automatically shortening names** doesn't have a perfect solution yet. Simply cutting names by character length may not look very good.
2. **Custom width** adjustment can be added. Users could set the width as a percentage of the total, or we could add a slider in the options page to allow adjustment from 10% to 100%, with a real-time preview.
3. **Hovering to show full size** is possible. However, if the group name is too long, it still might not be fully displayed. I think showing as much as possible without requiring the full name could work better, as users can still rely on the tooltip to see the entire group name.
4. **Tooltip showing the full name** can definitely be added without any issue.

**Comment by Daemonias** [comment]
> ### First Question:
> Are you referring to a **horizontal scrollbar**? If so, it might not be supported because the current minimum width is already quite wide. Adding a horizontal scrollbar could make the overall layout feel cluttered.

Yes I meant an horizontal scrollbar.
Or if not possible with a scrollbar maybe the possibility to scroll with the mousewheel.
Otherwise I don't have an option to select the tabs outside of the bar limit.

**Comment by ymlluo** [comment]
Maybe it's better not to use a scrollbar and use a multi-line display?

I need to make sure that the issue is that the group names are very long, which makes it difficult to distinguish them, right?

**Comment by Daemonias** [comment]
> Maybe it's better not to use a scrollbar and use a multi-line display?
Not sure how to do this but sounds like a posibility

> I need to make sure that the issue is that the group names are very long, which makes it difficult to distinguish them, right?
Yes. But even with no names I've gotten to the point that I can't access all tabs if one group with lots of tabs is open.
It pushes all tabs right of it to the right and sometimes out of bounds.
Or if it is too long I can't even access all tabs of the open group

**Comment by ymlluo** [comment]
Got it, I understand the issue.

I’ll include the following options in an upcoming update:

1. **Group width adjustment** (using a slider for easy customization).
2. **Multi-line display** for group names (limited by the width set in option 1).
3. **Hover to show full group names** (at 100% width, with multi-line display if configured). The tab icon will be moved below the group name.
4. **Tooltip showing the full group name**.

I believe these updates should address your concerns.

Do you have any other suggestions?

**Comment by Daemonias** [comment]
That should mostly do it..
But it still wouldn't help me if the bar is just full and some tabs are out of bounds.

Some way to scroll the bar would mitigate this. How about an invisible scrollbar?

**Comment by ymlluo** [comment]
Can you provide a screenshot with sensitive information blurred out? I want
to see what the problem looks like, which may help me understand the
problem better.

Daemonias ***@***.***> 于 2024年10月9日周三 23:25写道：

**Comment by ymlluo** [comment]
@Daemonias 
The new version v2.11.0 has been released. But I'm not sure if it solves your problem, you can try it, and if there are still other problems, you can provide a screenshot. I'll confirm the problem and then improve it
